
services:

# Add more containers below (nginx, postgres, etc.)
  back:
    container_name: back
    build:
      context: ./back
      dockerfile: Dockerfile
    ports:
      - 5000:5000

  mongo:
    container_name: mongo
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
    command: mongod --quiet --logpath /dev/null 
